services:
  InspiredMinds\ContaoMakerBundle\Maker\MakeContaoKickstart:
    arguments: 
      - '@maker.file_manager'
      - '@maker.autoloader_util'
    tags:
      - { name: maker.command }
  InspiredMinds\ContaoMakerBundle\Maker\MakeContaoManagerPlugin:
    tags:
      - { name: maker.command }